global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "steel-defect-api"
    static_configs:
      - targets: ["192.168.1.112:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
