# NEU Steel Defect Detection Dataset Configuration
# Bu dosya YOLOv8 eğitimi için veri seti yapılandırmasını tanımlar

# Veri setinin ana yolu (script'lerin çalışacağı yere göre)
# '.' işareti "bu klasörün içindeki" demektir
path: ./dataset

# Alt klasörler (path'e göre)
train: images/train
val: images/valid
test: images/test

# Sınıf Bilgileri
nc: 6 # Number of Classes (Toplam sınıf sayısı)
names:
  - crazing # 0
  - inclusion # 1
  - patches # 2
  - pitted_surface # 3
  - rolled-in_scale # 4
  - scratches # 5
